name: Create Preview environment

on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  create-preview-env:
    runs-on: ubuntu-latest

    steps:
      - uses: humanitec/preview-envs-action@v1
        with:
          humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
          humanitec-org: ${{ vars.HUMANITEC_ORG }}
          humanitec-app: ${{ vars.HUMANITEC_APP_NAME }}
          action: create
          github-token: ${{ secrets.GITHUB_TOKEN }}
