name: Deploy DEV
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
env:
  BASE_ENVIRONMENT: 'development'
  ENVIRONMENT_TYPE: 'development'
  ENVIRONMENT_ID: development
  ENVIRONMENT_NAME: development
  HUMCTL_VERSION: '0.23.2'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install humctl
        uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}
      - name: humctl score deploy
        run: |
          humctl score deploy \
              --deploy-config apps/score.deploy.yaml \
              --message "$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${{ github.event.pull_request.commits_url }}?per_page=10" | jq -r .[-1].commit.message)" \
              --workload-source-url-prefix "https://github.com/${{ github.repository }}/blob/${{ github.head_ref }}/apps" \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ secrets.HUMANITEC_ORG }} \
              --app ${{ vars.APP_NAME }} \
              --env ${{ env.ENVIRONMENT_ID }} \
              --wait
